apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inkspace-ingress-frontend
  namespace: inkspace
spec:
  ingressClassName: nginx
  rules:
  - host: inkspace.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: inkspace-frontend
            port:
              number: 80